import type { PRTrustBrief } from "@cartana/shared";

/**
 * Formats a PRTrustBrief object into GitHub-native Markdown,
 * ready to paste into GitHub Pull Request review comments.
 */
export function formatPRBriefAsGithubMarkdown(brief: PRTrustBrief): string {
  const trustBadgeEmoji =
    brief.trustLevel === "high" ? "🟢" : brief.trustLevel === "medium" ? "🟡" : "🔴";

  const riskSection =
    brief.riskAlerts.length > 0
      ? [
          "### ⚠️ Security & Architecture Risk Alerts",
          ...brief.riskAlerts.map(
            (a) =>
              `> [!${a.severity === "critical" ? "CAUTION" : "WARNING"}]\n> **${a.title}**\n> ${a.description}${
                a.affectedFiles && a.affectedFiles.length > 0
                  ? `\n> *Affected files:* \`${a.affectedFiles.join("`, `")}\``
                  : ""
              }`
          ),
          "",
        ].join("\n")
      : "";

  const verdictsSection = brief.verdicts
    .map((v) => {
      const statusEmoji =
        v.status === "covered"
          ? "✅"
          : v.status === "partial"
          ? "⚠️"
          : v.status === "missing"
          ? "❌"
          : "❓";

      const snippetBlock = v.evidenceSnippet
        ? `\n\n\`\`\`${v.evidenceFile?.endsWith(".py") ? "python" : "typescript"}\n// File: ${v.evidenceFile || "Source"}\n${v.evidenceSnippet}\n\`\`\``
        : "";

      return `<details>
<summary><b>${v.reqId}: ${v.title}</b> — ${statusEmoji} <code>${v.status.toUpperCase()}</code></summary>

> **Rationale:** ${v.rationale}
${v.evidenceFile ? `\n> **Evidence File:** \`${v.evidenceFile}\`` : ""}${snippetBlock}

</details>`;
    })
    .join("\n\n");

  return `## 🛡️ Cartana PR Trust Brief

| Metric | Value |
|---|---|
| **Trust Level** | ${trustBadgeEmoji} **${brief.trustLevel.toUpperCase()} TRUST** |
| **Coverage Score** | **${brief.coverageScore}%** |
| **Requirements** | Total: ${brief.totalRequirements} \| Covered: ${brief.coveredCount} \| Partial: ${brief.partialCount} \| Missing: ${brief.missingCount} |

### 📝 Executive Summary
${brief.summary}

${riskSection}
### 📋 Requirement Verification Matrix
${verdictsSection}

---
*Generated by Cartana AI Specification & Audit Copilot*`;
}

/** Helper to trigger browser file download. */
export function downloadFile(filename: string, content: string, contentType: string) {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
